name: Pre-commit-v2

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit
      run: python src/test.py